### PR TITLE
Add "waitEventsTimeout" and "WindowHint'DoubleBuffer"

### PR DESCRIPTION
**Pull request by OlivierSohn**
I used these 2 in my project, so I contribute them here, if it helps.

### CODE REVIEW

**Comment by Mokosha** [comment]
Excellent! Thank you!

**Comment by Mokosha** [comment]
In the future, feel free to open a pull request directly against bsl/GLFW-b. :)

**Comment by OlivierSohn** [comment]
You're welcome.

I wanted to open a PR against your repo because your PR https://github.com/bsl/GLFW-b/pull/79 summaries what needs to be done for 3.2.1, so I didn't want to open a "parallel" PR.

But maybe I'm missing something? Can you clarify why you think it's preferable to open a PR against bsl/GLFW-b ?

**Comment by Mokosha** [comment]
So the same way you opened a branch against this repo, you can open one against Upgrade-3.2.1 in bsl/GLFW-b. It won't add to the pull request from master to Upgrade-3.2.1. It would be a separate PR there.

**Comment by OlivierSohn** [comment]
Thanks I didn't know it was possible to do this!

**Pull request merged**
